# Generated by Django 3.2.6 on 2023-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_profile_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Идентификатор водителя Яндекс'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='driver_profile_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Идентификатор водителя Яндекс'),
        ),
    ]
