# Generated by Django 3.2.6 on 2025-10-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0002_auto_20231204_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
